### ISSUE TITLE
【错误反馈】（在此简单描述碰到的问题）

### ISSUE THREAD

**Issue by SAOGuangHu** [17TheWord/nonebot-plugin-mcqq#115]
### 运行环境

Python3.10

### NB插件及版本号

2.5.8

### MC插件及版本号

0.0.2

### 错误描述

Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\internal\driver\abstract.py", line 91, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\adapters\minecraft\adapter.py", line 71, in __init__
    self.minecraft_config: Config = get_plugin_config(Config)
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\plugin\__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "E:\3\Nonebot\.venv\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "E:\3\Nonebot\.venv\lib\site-packages\pydantic\type_adapter.py", line 373, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
minecraft_server_rcon
  Input should be a valid dictionary [type=dict_type, input_value='{\n    "Server": { # 服...# rcon 密码\n    }\n}', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/dict_type

### 报错日志（如果有）

```bash
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\internal\driver\abstract.py", line 91, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\adapters\minecraft\adapter.py", line 71, in __init__
    self.minecraft_config: Config = get_plugin_config(Config)
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\plugin\__init__.py", line 173, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "E:\3\Nonebot\.venv\lib\site-packages\nonebot\compat.py", line 225, in type_validate_python
    return TypeAdapter(type_).validate_python(data)
  File "E:\3\Nonebot\.venv\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "E:\3\Nonebot\.venv\lib\site-packages\pydantic\type_adapter.py", line 373, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
minecraft_server_rcon
  Input should be a valid dictionary [type=dict_type, input_value='{\n    "Server": { # 服...# rcon 密码\n    }\n}', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/dict_type
```

**Comment by 17TheWord** [comment]
不认真看wiki导致的
