### ISSUE TITLE
【错误反馈】导入插件时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [17TheWord/nonebot-plugin-mcqq#125]
### 运行环境

Ubuntu 22.04 LTS、Python3.10、Leaves-1.20.4

### NB插件及版本号

2.6.2

### MC插件及版本号

0.0.5

### 错误描述

启动导入插件时报错

### 报错日志（如果有）

```bash
11-03 03:12:07 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):
  File "/home/yuyue/nonebot/yuyue-nonebot/bot.py", line 18, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/plugin/load.py", line 133, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/plugin/load.py", line 67, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 205, in load_all_plugins
    return set(
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 206, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 257, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yuyue/.local/lib/python3.10/site-packages/nonebot_plugin_mcqq/__init__.py", line 4, in <module>
    from mcqq_tool.config import Config
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/config.py", line 197, in <module>
    class Config(BaseModel):
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/config.py", line 200, in Config
    mc_qq: MCQQConfig = MCQQConfig()
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "pydantic/main.py", line 1074, in pydantic.main.validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
  File "pydantic/fields.py", line 864, in pydantic.fields.ModelField.validate
    v, errors = self._apply_validators(v, values, loc, cls, self.pre_validators)
  File "pydantic/fields.py", line 1154, in pydantic.fields.ModelField._apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "pydantic/class_validators.py", line 304, in pydantic.class_validators._generic_validator_cls.lambda4
    return lambda cls, v, values, field, config: validator(cls, v)
  File "/home/yuyue/.local/lib/python3.10/site-packages/mcqq_tool/config.py", line 147, in validate_ignore_word_list
    if Path(cls.ignore_word_file).exists():
AttributeError: type object 'MCQQConfig' has no attribute 'ignore_word_file'. Did you mean: 'ignore_word_list'?
```

**Comment by 17TheWord** [comment]
检查mcqq-tool版本是否为最新

**Comment by YuYue-Amatsuki** [comment]
> 检查mcqq-tool版本是否为最新

已为最新版本
![Screenshot_2024-11-03-03-24-55-929_com.sonelli.juicessh-edit.jpg](https://github.com/user-attachments/assets/bd659de5-178b-422a-aa1c-50b12ee4b43e)

**Comment by 17TheWord** [comment]
怪诶，看看env中mcqq的配置项

**Comment by YuYue-Amatsuki** [comment]
> 怪诶，看看env中mcqq的配置项

![IMG_20241103_033551.jpg](https://github.com/user-attachments/assets/288f3f72-5a93-4cfb-a851-1e1faabc3bc0)

**Comment by 17TheWord** [comment]
事已至此，先睡觉了，太晚了

**Comment by hbj2457** [comment]
> 事已至此，先睡觉了，太晚了

大大，什么时候修好，我今天加了这个插件也是一样报错

**Comment by 17TheWord** [comment]
这我复现不出来啊，另外你配置项中，配了反向就不许与配正向了。
click、hover、component都是过时的配置项，已失效

![image](https://github.com/user-attachments/assets/c5571d02-d8a7-4fab-ac0e-c0d3349fddb5)

**Comment by YuYue-Amatsuki** [comment]
> 这我复现不出来啊，另外你配置项中，配了反向就不需要配正向了。
> click、hover、component都是过时的配置项，已失效
> 
> ![image](https://github.com/user-attachments/assets/c5571d02-d8a7-4fab-ac0e-c0d3349fddb5)
> 
删除上述配置项后仍报错
但我的配置项中并没有配置反向连接
```
minecraft_ws_urls = '{
    "SkyLineServer": ["ws://127.0.0.1:8089"],
    "SkyLineServer1": ["ws://127.0.0.1:8087"]
}'
```

**Comment by YuYue-Amatsuki** [comment]
完整的配置项如下，隐私信息作遮蔽处理
```
mc_qq__server_dict = '{
    "SkyLineServer": {
        "group_list": [
            {
                "group_id": "97*****92",
                "adapter": "onebot",
                "bot_id": "25*****89"
            }
        ],
        "rcon_msg": false,
        "rcon_cmd": true
    },
    "SkyLineServer1": {
        "group_list": [
            {
                "group_id": "97*****92",
                "adapter": "onebot",
                "bot_id": "25*****89"
            }
        ],
        "rcon_msg": false,
        "rcon_cmd": true
    }

}'
minecraft_server_rcon = '{
    "SkyLineServer": {
        "enable_rcon": true,
        "rcon_port": ***,
        "rcon_password": "***"
    },
    "SkyLineServer1": {
        "enable_rcon": true,
        "rcon_port": ***,
        "rcon_password": "***"
    }
}'
minecraft_ws_urls = '{
    "SkyLineServer": ["ws://127.0.0.1:8089"],
    "SkyLineServer1": ["ws://127.0.0.1:8087"]
}'
mc_qq__cmd_whitelist = ["list", "tps", "mspt"]
mc_qq__say_way = "："
mc_qq__chat_image_enable = true
mc_qq__rcon_result_to_image = true
```

**Comment by 17TheWord** [comment]
包意思，看错了。
我这边新的环境没有出现问题，你有没有尝试过全新环境？
吃过饭我继续测试下

**Comment by 17TheWord** [comment]
已找到问题，pydantic V1 导致的，等待修复

**Comment by 17TheWord** [comment]
请更新工具包 `pip install mcqq-tool==1.3.4`
