### ISSUE TITLE
【错误反馈】TypeError报错

### ISSUE THREAD

**Issue by Cloudwhile** [17TheWord/nonebot-plugin-mcqq#13]
### 运行环境

Windows Server 2022 

### 插件版本

nonebot-plugin-mcqq

### 插件版本号

V1.0.0

### 错误描述

无法加载插件

### 报错日志（如果有）

```bash
10-01 21:07:55 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "c:\program files\python\lib\site-packages\uvicorn\config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\program files\python\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\bot.py", line 35, in <module>
    nonebot.load_plugin('nonebot_plugin_mcqq')
  File "c:\program files\python\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "c:\program files\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\program files\python\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\__init__.py", line 25, in <module>
    async def handle_first_receive(bot: Bot, event: GroupMessageEvent | GuildMessageEvent):
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'ModelMetaclass'
```

**Comment by 17TheWord** [comment]
请提供Python版本

**Comment by 17TheWord** [comment]
问题已在 [Issues11](https://github.com/17TheWord/nonebot-plugin-mcqq/issues/11) 出现，将在下个版本修复

**Comment by 17TheWord** [comment]
已在 [`V0.1.1`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/V0.1.1) 修复
