### ISSUE TITLE
【错误反馈】服务器发送到群第一条消息之后连接断开

### ISSUE THREAD

**Issue by Cloudwhile** [17TheWord/nonebot-plugin-mcqq#14]
### 运行环境

Windows Server 2022 

### Python版本

python 3.8

### 插件版本

nonebot-plugin-mcqq

### 插件版本号

V0.1.1

### 错误描述

进入服务器后成功发了信息到群聊，但是只能发这一条，之后就显示MC_QQ断开连接。

### 报错日志（如果有）

```bash
10-02 21:53:38 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_mcqq, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\program files\python\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\program files\python\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\program files\python\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\program files\python\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "c:\program files\python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\__init__.py", line 27, in handle_first_receive
    await send_msg_to_mc(bot=bot, event=event)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\data_source.py", line 53, in send_msg_to_mc
    await websocket.send(msgJson)
  File "c:\program files\python\lib\site-packages\websockets\legacy\protocol.py", line 620, in send
    await self.ensure_open()
  File "c:\program files\python\lib\site-packages\websockets\legacy\protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
```

**Comment by 17TheWord** [comment]
能否提供复现情况？（如配置信息等更详细的内容）
我无法复现问题

**Comment by Cloudwhile** [comment]
请问你需要什么配置信息和详细的内容

**Comment by Cloudwhile** [comment]
10-03 11:39:43 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "c:\program files\python\lib\site-packages\nonebot\internal\driver\driver.py", line 140, in _run_hook
    await asyncio.gather(*coros)
  File "c:\program files\python\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
    return await coro
  File "c:\program files\python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\__init__.py", line 17, in on_start
    await on_connect(bot=bot)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\data_source.py", line 43, in on_connect
    await send_msg_to_qq(bot=bot, recv_msg=recv_msg)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\utils.py", line 14, in send_msg_to_qq
    await bot.call_api("send_guild_channel_msg", guild_id=per_guild[0],
IndexError: list index out of range

**Comment by 17TheWord** [comment]
这是重启过bot之后么？
重启之后还是只发送一条消息就断开连接么？

**Comment by Cloudwhile** [comment]
对

**Comment by Cloudwhile** [comment]
盲猜是频道问题？

**Comment by 17TheWord** [comment]
> 10-03 11:39:43 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
>     return self._bootstrap(parent_sentinel)
>   File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\program files\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
>     target(sockets=sockets)
>   File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
>     self.run_forever()
>   File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
>     self._run_once()
>   File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
>     handle._run()
>   File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
>     self._context.run(self._callback, *self._args)
>  File "c:\program files\python\lib\site-packages\nonebot\internal\driver\driver.py", line 140, in _run_hook
>     await asyncio.gather(*coros)
>   File "c:\program files\python\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
>     return await coro
>   File "c:\program files\python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
>     return await self.call(**values)
>   File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\__init__.py", line 17, in on_start
>     await on_connect(bot=bot)
>   File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\data_source.py", line 43, in on_connect
>     await send_msg_to_qq(bot=bot, recv_msg=recv_msg)
>   File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\utils.py", line 14, in send_msg_to_qq
>     await bot.call_api("send_guild_channel_msg", guild_id=per_guild[0],
> IndexError: list index out of range
> 

把频道的配置删掉

**Comment by 17TheWord** [comment]
第一个问题我会尝试在发送时加入断线重连

**Comment by Cloudwhile** [comment]
【[0;31;22mBuliRua[m】444[m，发送的消息有点问题

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/193498564-ba01e184-ebc5-47ff-bdcf-57afb95cd3c8.png)

**Comment by 17TheWord** [comment]
> 【[0;31;22mBuliRua[m】444[m，发送的消息有点问题

这个日志截全一点，我看不出来这是哪里的问题

**Comment by Cloudwhile** [comment]
这是q群里的发送记录

**Comment by 17TheWord** [comment]
> ![image](https://user-images.githubusercontent.com/86512509/193498564-ba01e184-ebc5-47ff-bdcf-57afb95cd3c8.png)
> 

还是不能够理解
这是什么情况下出现的？
服务端发送到群还是群发送到bot？
日志前后有无内容？

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/193498917-adba5831-2482-4434-a5b0-a7545cc12b5b.png)
![image](https://user-images.githubusercontent.com/86512509/193498943-cb14b513-a2a0-46a6-a30e-e2522d0d4a2d.png)

**Comment by 17TheWord** [comment]
好的
后续会去修复（虽然我也不知道是什么问题）

**Comment by Cloudwhile** [comment]
这是Go-cqhttp中的信息
发送到群*****的消息: 【[2022-10-03 11:51:51] [WARNING]: 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
[2022-10-03 11:52:18] [WARNING]: 处理 WebSocket 请求时出现错误: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

**Comment by Cloudwhile** [comment]
二创的插件也有问题(不知道为什么我的问题特别多

**Comment by Cloudwhile** [comment]
10-03 12:35:37 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
> File "c:\program files\python\lib\site-packages\nonebot\internal\driver\driver.py", line 140, in _run_hook
    await asyncio.gather(*coros)
  File "c:\program files\python\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
    return await coro
  File "c:\program files\python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\__init__.py", line 17, in on_start
    await on_connect(bot=bot)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\data_source.py", line 43, in on_connect
    await send_msg_to_qq(bot=bot, recv_msg=recv_msg)
  File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\utils.py", line 14, in send_msg_to_qq
    await bot.call_api("send_guild_channel_msg", guild_id=per_guild[0],
IndexError: list index out of range
![image](https://user-images.githubusercontent.com/86512509/193502485-714923de-79b0-41da-a503-b1d854b2320b.png)
![image](https://user-images.githubusercontent.com/86512509/193502543-c1d50387-3eea-490c-a0aa-679afd4ba48f.png)
![image](https://user-images.githubusercontent.com/86512509/193502668-1513c68a-deb9-44a8-adef-fb0b6ca9c279.png)

**Comment by 17TheWord** [comment]
> 10-03 12:35:37 [ERROR] nonebot | Error when running WebSocketConnection hook. Running cancelled!
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "c:\program files\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "c:\program files\python\lib\multiprocessing\spawn.py", line 129, in _main
>     return self._bootstrap(parent_sentinel)
>   File "c:\program files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "c:\program files\python\lib\multiprocessing\process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\program files\python\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
>     target(sockets=sockets)
>   File "c:\program files\python\lib\site-packages\uvicorn\server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "c:\program files\python\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "c:\program files\python\lib\asyncio\base_events.py", line 603, in run_until_complete
>     self.run_forever()
>   File "c:\program files\python\lib\asyncio\base_events.py", line 570, in run_forever
>     self._run_once()
>   File "c:\program files\python\lib\asyncio\base_events.py", line 1859, in _run_once
>     handle._run()
>   File "c:\program files\python\lib\asyncio\events.py", line 81, in _run
>     self._context.run(self._callback, *self._args)
> > File "c:\program files\python\lib\site-packages\nonebot\internal\driver\driver.py", line 140, in _run_hook
>     await asyncio.gather(*coros)
>   File "c:\program files\python\lib\site-packages\nonebot\utils.py", line 138, in run_coro_with_catch
>     return await coro
>   File "c:\program files\python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
>     return await self.call(**values)
>   File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\__init__.py", line 17, in on_start
>     await on_connect(bot=bot)
>   File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\data_source.py", line 43, in on_connect
>     await send_msg_to_qq(bot=bot, recv_msg=recv_msg)
>   File "c:\program files\python\lib\site-packages\nonebot_plugin_mcqq\utils.py", line 14, in send_msg_to_qq
>     await bot.call_api("send_guild_channel_msg", guild_id=per_guild[0],
> IndexError: list index out of range
> ![image](https://user-images.githubusercontent.com/86512509/193502485-714923de-79b0-41da-a503-b1d854b2320b.png)
> ![image](https://user-images.githubusercontent.com/86512509/193502543-c1d50387-3eea-490c-a0aa-679afd4ba48f.png)
> ![image](https://user-images.githubusercontent.com/86512509/193502668-1513c68a-deb9-44a8-adef-fb0b6ca9c279.png)
> 

二创的话应该去二创提交issue

**Comment by Cloudwhile** [comment]
这个不是二创的

**Comment by 17TheWord** [comment]
> 这个不是二创的
> 

我的插件并没有填写日志路径的配置

**Comment by Cloudwhile** [comment]
加个qq？

**Comment by Cloudwhile** [comment]
![image](https://user-images.githubusercontent.com/86512509/193506761-f6139715-4142-4f99-9d02-606d891d5c3b.png)
sm
上面这个是你插件的配置，下面是别的

**Comment by 17TheWord** [comment]
> 加个qq？

你发吧

**Comment by Cloudwhile** [comment]
3245567560


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月3日(周一) 中午1:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [17TheWord/nonebot-plugin-mcqq] 【错误反馈】服务器发送到群第一条消息之后连接断开 (Issue #14)




  
加个qq？
  
你发吧
 
&mdash;

**Comment by Cloudwhile** [comment]
3245567560
