### ISSUE TITLE
【错误反馈】消息只能单向传递

### ISSUE THREAD

**Issue by aurorataro** [17TheWord/nonebot-plugin-mcqq#17]
### 运行环境

Ubuntu 22 LTS

### Python版本

3.10

### 插件版本

nonebot-plugin-mcqq-mcrcon

### 插件版本号

latest

### QQ消息转发至服务器  正常✔
![image](https://user-images.githubusercontent.com/62366575/197735776-5180be65-95f0-4564-90f1-0bf97ab83fb7.png)
```
10-25 17:11:15 [SUCCESS] nonebot_plugin_mcqq_mcrcon | [MC_QQ]丨已成功连接到 MC_QQ WebSocket 服务器！
```
```
10-25 17:17:44 [SUCCESS] nonebot | OneBot V11 * | [message.group.normal]: Message 110821724 from *@[群:*] "[CQ:at,qq=*] 先进单人"
10-25 17:17:44 [DEBUG] nonebot | Checking for matchers in priority 1...
10-25 17:17:44 [DEBUG] nonebot | Checking for matchers in priority 5...
10-25 17:17:44 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mcqq_mcrcon)
10-25 17:17:44 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mcqq_mcrcon)
10-25 17:17:44 [DEBUG] nonebot | Running handler Dependent(call=handle_first_receive)
10-25 17:17:44 [DEBUG] nonebot | OneBot V11 | Calling API get_group_member_info
10-25 17:17:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mcqq_mcrcon) running complete
10-25 17:17:45 [DEBUG] nonebot | Stop event propagation
```
```
*@*:~/*/server$ ./mcqq.sh
java.nio.file.NoSuchFileException: .\logs\
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:115)
        at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
        at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266)
        at java.base/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
        at java.base/java.lang.Thread.run(Thread.java:833)
[MC_QQ]：WebSockets 服务端已启动
[MC_QQ]：一个来自：127.0.0.1的新连接。
```
### 服务器消息转发至QQ  异常❌
mcqq.jar 和nonebot 没有任何提示

按照文档一步步设置，已确定rcon密码、端口等未设置错误

**Comment by aurorataro** [comment]
补充
**nonebot .env.dev 文件**
```
HOST=127.0.0.1
PORT=8080
LOG_LEVEL=DEBUG
FASTAPI_RELOAD=true

MC_QQ_GROUP_LIST=[*********(打码)]
MC_QQ_IP="127.0.0.1"
MC_QQ_WS_PORT=8765
MC_QQ_MCRCON_PASSWORD="1"
MC_QQ_MCRCON_PORT=25575
```

**server.properties**
```
rcon.port=25575
enable-rcon=true
rcon.password=1
```

**Comment by 17TheWord** [comment]
看来我的issue模板还需要改进，之后会再改一下模板以了解更多信息。

mc用的是非插件端？原版端还是Forge？

**Comment by aurorataro** [comment]
使用Fabric端 不支持插件

**Comment by 17TheWord** [comment]
Fabric暂未做出适配，因为我并没有Fabric的需求等。

实际上最初也是只有原版端，Forge也是在issue中新增的。

如此看来Fabric的日志格式与Forge端、原版端的日志格式都不相同。

接下来会将Fabric端提上日程。

可以的话请回复完整的日志聊天、加入/退出事件信息。

**Comment by 17TheWord** [comment]
有急需的话我可以先做一个Fabric的测试版私发你使用。

**Comment by idun886** [comment]
支持

**Comment by 17TheWord** [comment]
Fabric端已在 [`v1.0.5`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v1.0.5) 中支持
