### ISSUE TITLE
【错误反馈】linux无法使用Minecraft server rcon插件

### ISSUE THREAD

**Issue by koi5hi** [17TheWord/nonebot-plugin-mcqq#21]
### 运行环境

debian11

### 插件版本

Minecraft_Server

### 插件版本号

v0.1.4

### 错误描述

![QQ截图20221223074113](https://user-images.githubusercontent.com/50271567/209243339-9d8cee60-c119-41af-9040-c3458b5672be.png)
linux下无法使用，希望能够自定义路径来解决这个错误。

### 报错日志（如果有）

```bash
java.nio.file.NoSuchFileException: .\logs\
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by 17TheWord** [comment]
已在 [`v0.1.5`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.1.5) 更新，我没有这样的使用环境所以并未进行测试

配置文件中已新增自定义文件路径
```yml
# 日志路径
# Windows 请用 ".\\logs\\"
# Linux 请用 "./logs/"
log_local: "./logs/"
```
如有问题请继续回复

**Comment by koi5hi** [comment]
经本地测试，目前已能够读取到日志文件。（请无视服务器插件报错信息，就几个朋友玩所以没弄）
![QQ截图20221223164804](https://user-images.githubusercontent.com/50271567/209303916-b32d2a03-650b-4b7e-a7e8-bf5710815c93.png)


但是目前出现了其他问题，在启动之后会提示这个错误
![QQ截图20221223163720](https://user-images.githubusercontent.com/50271567/209303469-24cb4568-78a4-4b47-9a41-31b559f2a57a.png)
ws无法成功连接，配置文件确认无误。（因为在旧版本能够启动ws服务，并且bot端也成功连接）
![QQ截图20221223164615](https://user-images.githubusercontent.com/50271567/209303633-ce087d2f-d544-47f9-b7d5-8fc98c6f8e9b.png)

但是玩家如果发送文字消息后，会出现另外一个错误。并且断开了日志监听状态
![QQ截图20221223165241](https://user-images.githubusercontent.com/50271567/209304617-75d88910-1696-47dc-85ef-60c9a0ee844d.png)

总结，文本读取问题已修复，但是出现其他2个错误，一个是启动时ws的报错，另一个错误是玩家发送文本后出错。

**Comment by 17TheWord** [comment]
读取日志是通过对日志在长度上的截取后发送的。
你使用的是什么服务端，这些貌似没有写在issue中，报错内容大致与端的日志长度有关。

**Comment by koi5hi** [comment]
我用的是arclight-forge-1.16.5，插件详情没写支持这个服务端，我尝试了后就出现如上错误

**Comment by 17TheWord** [comment]
我有发现这款服务端支持Bukkit插件，你有尝试过使用spigot插件版本的mcqq吗？

**Comment by koi5hi** [comment]
因为插件版本只有1.16.5的版本，所以目前用1.16.5的版本的插件
[v0.0.4](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.0.4)测试了
![QQ截图20221224130118](https://user-images.githubusercontent.com/50271567/209422229-37f18f13-3c5e-4220-a168-7e0c673f3daf.png)
同一个服务端。在windows下可以成功加载并且功能正常。

而在linux下，加载插件后，在websocket这里依旧是报错。
![QQ截图20221224130316](https://user-images.githubusercontent.com/50271567/209422305-8aab0683-1dff-4969-9e3c-3fc2f1fc6bb5.png)



[24十二月2022 12:54:26.415] [Server thread/INFO] [MC_QQ/]: Enabling MC_QQ v1.0-SNAPSHOT
[24十二月2022 12:54:26.445] [Server thread/INFO] [STDERR/]: [org.slf4j.helpers.Util:report:128]: SLF4J: Class path contains multiple SLF4J bindings.
[24十二月2022 12:54:26.446] [Server thread/INFO] [STDERR/]: [org.slf4j.helpers.Util:report:128]: SLF4J: Found binding in [jar:file:/home/mc/mcc/NC/arclight-forge-1.16.5-1.0.24-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[24十二月2022 12:54:26.446] [Server thread/INFO] [STDERR/]: [org.slf4j.helpers.Util:report:128]: SLF4J: Found binding in [modjar://arclight/org/slf4j/impl/StaticLoggerBinder.class]
[24十二月2022 12:54:26.446] [Server thread/INFO] [STDERR/]: [org.slf4j.helpers.Util:report:128]: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[24十二月2022 12:54:26.450] [Server thread/INFO] [STDERR/]: [org.slf4j.helpers.Util:report:128]: SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[24十二月2022 12:54:26.471] [Server thread/INFO] [Console/]: [MC_QQ]：已加载
[24十二月2022 12:54:26.475] [Server thread/INFO] [MySkin/]: Enabling MySkin v3.3
[24十二月2022 12:54:26.481] [WebSocketSelector-128/ERROR] [org.java_websocket.server.WebSocketServer/]: Shutdown due to fatal error
java.net.BindException: 无法指定被请求的地址
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_351]
	at sun.nio.ch.Net.bind(Net.java:438) ~[?:1.8.0_351]
	at sun.nio.ch.Net.bind(Net.java:430) ~[?:1.8.0_351]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:225) ~[?:1.8.0_351]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_351]
	at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:567) [MC_QQ_1.16.5-1.0-SNAPSHOT.jar:?]
	at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:367) [MC_QQ_1.16.5-1.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]


rcon版本和插件版本都是websocket错误，仅在linux中出现这问题

**Comment by 17TheWord** [comment]
已在 [`v0.1.5`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v0.1.5) 新增适用于 `1.16.5` 版本服务端的插件，测试在 `1.19.1` 也成功使用。

**Comment by koi5hi** [comment]
非常抱歉。
我之前的java版本太低，所以导致插件加载失败。

现在已经升级了java版本，Bukkit插件版已成功在linux加载并且运行。（rcon版依旧出错）

端口也成功开放了，但是监听的ip只在本地127.0.0.1
能否让端口暴露至公网，让机器人可以远程连接服务端这边。
成
![1234](https://user-images.githubusercontent.com/50271567/209434167-240fc4f5-4b48-47ab-baa8-99c4c69e38c6.png)
![1234](https://user-images.githubusercontent.com/50271567/209434256-f844e4a8-176a-4a72-bca9-a58bf15f3a36.png)

**Comment by 17TheWord** [comment]
暴露在公网只需要将ip写成 `0.0.0.0` 即可

**Comment by 17TheWord** [comment]
没有问题的话就关闭了
