### ISSUE TITLE
【错误反馈】读取 mc_qq_mcrcon_rcon_list 时 KeyError: ''

### ISSUE THREAD

**Issue by H-xiaoH** [17TheWord/nonebot-plugin-mcqq#30]
### 运行环境

Windows 10、Python 3.10.9、Fabric-1.18.2

### 插件版本

nonebot-plugin-mcqq-mcrcon

### 插件版本号

v1.0.6

### 错误描述

.env.prod
```text
MC_QQ_WS_IP="127.0.0.1"
MC_QQ_WS_PORT=8765
MC_QQ_SEND_GROUP_NAME=false
MC_QQ_DISPLAY_SERVER_NAME=true
MC_QQ_SERVERS_LIST = [{"server_name": "服务器", "group_list": [number]}]
MC_QQ_MCRCON_PASSWORD="rcon"
MC_QQ_MCRCON_RCON_LIST={"服务器": 25575}
MC_QQ_MCRCON_GUILD_ADMIN_ROLES=["服务器OP"]
```

server.properties
```text
rcon.port=25575
enable-rcon=true
rcon.password=rcon
```

### 报错日志（如果有）

nonebot2
```bash
01-16 04:06:04 [SUCCESS] nonebot_plugin_mcqq_mcrcon | [MC_QQ_Rcon]丨[Server:] 已连接至 WebSocket 服务器
connection handler failed
Traceback (most recent call last):
  File "C:\Users\HxiaoH\Downloads\nb2\.venv\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "C:\Users\HxiaoH\Downloads\nb2\.venv\lib\site-packages\nonebot_plugin_mcqq_mcrcon\data_source.py", line 35, in ws_client
    get_mc_qq_mcrcon_rcon_list()[msg['server_name']]
KeyError: ''
01-16 04:06:05 [SUCCESS] nonebot_plugin_mcqq_mcrcon | [MC_QQ_Rcon]丨[Server:] 已连接至 WebSocket 服务器
connection handler failed
Traceback (most recent call last):
  File "C:\Users\HxiaoH\Downloads\nb2\.venv\lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "C:\Users\HxiaoH\Downloads\nb2\.venv\lib\site-packages\nonebot_plugin_mcqq_mcrcon\data_source.py", line 35, in ws_client
    get_mc_qq_mcrcon_rcon_list()[msg['server_name']]
KeyError: ''
...
```

MC_QQ_Minecraft_Server.jar
```bash
[MC_QQ]丨已成功连接 WebSocket 服务器。
[MC_QQ]丨WebSocket 连接已断开,正在第 1 次重新连接。
[MC_QQ]丨已成功连接 WebSocket 服务器。
[MC_QQ]丨WebSocket 连接已断开,正在第 1 次重新连接。
[MC_QQ]丨已成功连接 WebSocket 服务器。
[MC_QQ]丨WebSocket 连接已断开,正在第 1 次重新连接。
...
```

**Comment by 17TheWord** [comment]
我看了一下main分支的代码，里面并没有msg这个变量，你看样子你应该使用1.0.7的nb端插件？尝试升级一下。

**Comment by 17TheWord** [comment]
已在 [`v1.0.8`](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/tag/v1.0.8) 更新

**Comment by H-xiaoH** [comment]
MC_QQ_Minecraft_Server.jar (v1.0.8)
```text
$ java -jar MC_QQ_Minecraft_Server.jar
MC_QQ_Minecraft_Server.jar中没有主清单属性
```

```text
$ java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```
