### ISSUE TITLE
【错误反馈】在MC服务端配置ws地址为域名而非ip时无法成功连接nonebot端

### ISSUE THREAD

**Issue by dixiatielu** [17TheWord/nonebot-plugin-mcqq#40]
### 运行环境

Ubuntu 22.04 LTS、Python3.10、PufferFIsh-1.19.3

### NB插件及版本号

nonebot-plugin-mcqq 1.0.9

### MC插件及版本号

MC_QQ_Spigot_1.14+ 1.0.9

### 错误描述

MC服务端的`websocket_url`配置填写域名时
```yaml
# 请在冒号后填写 WebSocket 地址。
# 若不填写，则地址默认为 127.0.0.1 ，端口默认为 8765
# 若使用插件，请填写：ws://127.0.0.1:8765
# 若使用适配器，请填写：ws://127.0.0.1:8765/spigot/ws
websocket_url: "ws://qbot.example.com:8765"
```
`nonebot`端控制台循环报错，查看MC端控制台也在不断重连
```
[16:17:43 INFO]: [MC_QQ] WebSocket 连接已断开,正在第 4 次重新连接。
[16:17:46 INFO]: [MC_QQ] WebSocket 连接已断开,正在第 5 次重新连接。
[16:17:49 INFO]: [MC_QQ] WebSocket 连接已断开,正在第 6 次重新连接。
[16:17:52 INFO]: [MC_QQ] WebSocket 连接已断开,正在第 7 次重新连接。
```
Nonebot端报错：
```
01-30 16:17:52 [SUCCESS] nonebot_plugin_mcqq | [MC_QQ]丨[Server:纯净生存] 已连接至 WebSocket 服务器
connection handler failed
Traceback (most recent call last):
  File "/root/dxtl_bot/dxtlBot/.venv/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/root/dxtl_bot/dxtlBot/.venv/lib/python3.10/site-packages/nonebot_plugin_mcqq/data_source.py", line 48, in ws_client
    CLIENTS.remove({"server_name": server_name, "ws_client": websocket})
ValueError: list.remove(x): x not in list
```
将域名替换为ip后：
```yaml
# 请在冒号后填写 WebSocket 地址。
# 若不填写，则地址默认为 127.0.0.1 ，端口默认为 8765
# 若使用插件，请填写：ws://127.0.0.1:8765
# 若使用适配器，请填写：ws://127.0.0.1:8765/spigot/ws
websocket_url: "ws://123.123.123.123:8765"
```
正常连接

**Comment by dixiatielu** [comment]
直接用ip吧，应该是websocket 会抛出异常的原因
