### ISSUE TITLE
【错误反馈】mcrcon缺少aiomcrcon依赖

### ISSUE THREAD

**Issue by OnlyblackTea** [17TheWord/nonebot-plugin-mcqq#44]
### 运行环境

Ubuntu 20.04 LTS、Python 3.8

### NB插件及版本号

nonebot-plugin-mcqq-mcrcon

### MC插件及版本号

MC_QQ_Forge_1.19.1-1.0.9.jar

### 错误描述

加载NB插件失败，缺少依赖

### 报错日志（如果有）
```
02-19 12:35:11 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq_mcrcon"
Traceback (most recent call last):
  File "bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/vbot/lib/python3.8/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/vbot/lib/python3.8/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/vbot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/home/vbot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/vbot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/home/vbot/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/vbot/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vbot/lib/python3.8/site-packages/nonebot_plugin_mcqq_mcrcon/__init__.py", line 7, in <module>
    from .data_source import (
  File "/home/vbot/lib/python3.8/site-packages/nonebot_plugin_mcqq_mcrcon/data_source.py", line 3, in <module>
    import aiomcrcon
ModuleNotFoundError: No module named 'aiomcrcon'
```
_No response_

**Comment by 17TheWord** [comment]
pip install aio-mc-rcon

**Comment by 17TheWord** [comment]
如果问题解决，请关闭issue
