### ISSUE TITLE
【功能建议】支持混合端？

### ISSUE THREAD

**Issue by youlanan** [17TheWord/nonebot-plugin-mcqq#46]
### 插件版本

nonebot-plugin-mcqq-mcrcon

### 插件版本号

v1.1.1 -  MC_QQ_Spigot_1.12.jar 

### 功能建议

[21:55:16 ERROR]: 无法加载位于文件夹 plugins 中的 plugins\MC2QQSpigot_1.12.jar ，因为插件无效
 org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.scareye.mcqq.MC_QQ'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:74) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126) ~[JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323) ~[SimplePluginManager.class:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245) [SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:392) [CraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:826) [?:1.8.0_352]
Caused by: java.lang.ClassNotFoundException: com.scareye.mcqq.MC_QQ
        at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_352]
        at java.lang.Class.forName(Class.java:424) ~[?:1.8.0_352]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:72) ~[PluginClassLoader.class:?]
        ... 8 more

### 额外信息（可选）

墨端1.12.2没加载上...其他端没试，或许这是个错误？

**Comment by 17TheWord** [comment]
已在 [v1.1.1](https://github.com/17TheWord/nonebot-plugin-mcqq/releases/download/v1.1.1/MC_QQ_Spigot_1.12.2.jar) 重新发布，前往下载即可。将Java从11降低至8。
