### ISSUE TITLE
【错误反馈】（在此简单描述碰到的问题）

### ISSUE THREAD

**Issue by MingriLingran** [17TheWord/nonebot-plugin-mcqq#48]
### 运行环境

Python 3.11.3 

### NB插件及版本号

mcport-0.1.6

### MC插件及版本号

1.19.2 paper端

### 错误描述

群里无法执行指令。快捷指令也无响应。本人非专业的开发者希望能给个解决办法谢谢

### 报错日志（如果有）

```bash
04-30 19:27:45 [SUCCESS] nonebot | OneBot V11 1704673814 | [message.group.normal]: Message -697577047 from 3035348107@[ 群:761718716] '执行命令list'
04-30 19:27:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-mcport.mcrcon)
04-30 19:27:45 [INFO] nonebot-plugin-mcport | 有人触发"执行命令"指令了哦~
04-30 19:27:45 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-mcport.mcrcon) running complete
04-30 19:27:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-mcport.mcrcon) failed.
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\我的世界服务端\KFC\zx\.venv\Lib\site-packages\nonebot-plugin-mcport\mcrcon.py", line 54, in mingling
    if event.user_id in zr:
TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by 17TheWord** [comment]
首先这个插件不是我的，是 [Proviasw](https://github.com/Proviasw/nonebot-plugin-mcport/commits?author=Proviasw) 的 [nonebot-plugin-mcport](https://github.com/Proviasw/nonebot-plugin-mcport)
看样子是要一个str值而非int值，类型错了

**Comment by 17TheWord** [comment]
如果没有其他问题的话，就关闭了
