### ISSUE TITLE
bug【错误反馈】（在此简单描述碰到的问题）不能用

### ISSUE THREAD

**Issue by kroazi** [17TheWord/nonebot-plugin-mcqq#55]
### 运行环境

Ubuntu server 22.04 lts

### NB插件及版本号

最新版

### MC插件及版本号

最新版

### 错误描述

启动直接报错

### 报错日志（如果有）

```bash
07-03 05:06:26 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/nonebot_plugin_mcqq/__init__.py", line 13, in <module>
    from mcqq_tool.common import GUILD_ADMIN
  File "/data1/Servers/NoneBot/MengPi/.venv/lib/python3.10/site-packages/mcqq_tool/common.py", line 12, in <module>
    plugin_config: Config = Config.parse_obj(get_driver().config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
mc_qq_server_list
  value is not a valid list (type=type_error.list)
07-03 05:06:26 [ERROR] nonebot_plugin_mcqq_server | mc_log_path 地址设置错误，D:\MinecraftServer\logs/latest.log 不存
```

**Comment by 17TheWord** [comment]
这个应该不是我的插件，[KarisAya/nonebot_plugin_mcqq_server](nonebot_plugin_mcqq_server )

**Comment by kroazi** [comment]
第一行07-03 05:06:26 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):不是写的mcqq吗

**Comment by 17TheWord** [comment]
- [KarisAya/nonebot_plugin_mcqq_server](https://github.com/KarisAya/nonebot_plugin_mcqq_server) 没有 require("nonebot_plugin_guild_patch")
