### ISSUE TITLE
【错误反馈】游戏中发送消息没显示，服务器后台报错

### ISSUE THREAD

**Issue by nanchennn** [17TheWord/nonebot-plugin-mcqq#73]
### 运行环境

windows server2022 Python3.11 forge-1.20.1

### NB插件及版本号

2.5.4

### MC插件及版本号

2.5.4

### 错误描述

游戏中发送消息没显示，服务器后台报错

### 报错日志（如果有）

```bash
[ForkJoinPool.commonPool-worker-4/ERROR] [net.minecraft.util.FutureChain/]: Chain link failed, continuing to next one
java.lang.NullPointerException: Cannot invoke "com.github.theword.WSClient.sendMessage(String)" because "com.github.theword.MCQQ.wsClient" is null
	at com.github.theword.EventProcessor.onServerChat(EventProcessor.java:27) ~[?:?]
	at com.github.theword.__EventProcessor_onServerChat_ServerChatEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:412) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.lambda$getServerChatSubmittedDecorator$0(ForgeHooks.java:422) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by 17TheWord** [comment]
如何稳定复现？
我这边使用nb插件2.5.3版本的release中的mod，正常运行
