### ISSUE TITLE
【错误反馈】无法加载NoneBot插件

### ISSUE THREAD

**Issue by Zhou-Shilin** [17TheWord/nonebot-plugin-mcqq#78]
### 运行环境

Ubuntu 22.04 LTS

### NB插件及版本号

NoneBot CLI 1.3.0 / MC_QQ lastest

### MC插件及版本号

MC_QQ_Spigot_1.14-latest-2.5.3

### 错误描述

无法加载nonebot插件
![E57C833A-84DE-4831-BBFA-6ED7C7B66AFD](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/86581525/ed87d9f1-20f2-44b7-b035-7539a18cb7a7)

### 报错日志（如果有）

```bash
03-09 19:09:03 [ERROR] nonebot | Failed to import "nonebot_plugin_mcqq"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot_plugin_mcqq/__init__.py", line 3, in <module>
    require("nonebot_plugin_guild_patch")
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_guild_patch"!
```

**Comment by Zhou-Shilin** [comment]
已解决，降级pydanmic为1.10即可。记得一定要进venv降级～

**Comment by 17TheWord** [comment]
经测试原因是频道补丁 `nonebot-plugin-guild-patch` 已归档，暂未支持 `Pydantic V2`
