### ISSUE TITLE
【错误反馈】403 Forbidden

### ISSUE THREAD

**Issue by Zhou-Shilin** [17TheWord/nonebot-plugin-mcqq#79]
### 运行环境

Ubuntu 22.04 LTS

### NB插件及版本号

NoneBot CLI 1.3.0 / MC_QQ lastest

### MC插件及版本号

MC_QQ_Spigot_1.14-latest-2.5.3

### 错误描述

![F0DECFC4-1E20-454A-8F22-6A200A046454](https://github.com/17TheWord/nonebot-plugin-mcqq/assets/86581525/f79c8eff-24b3-4c1b-b0f8-c8431454fef5)
Minecraft端连接Nonebot的ws失败，nonebot端显示403；插件已成功加载；nonebot除403外全程无其他报错。

### 报错日志（如果有）

```bash
03-10 10:34:16 [INFO] websockets | connection rejected (403 Forbidden)
03-10 10:34:16 [INFO] websockets | connection closed
```

**Comment by 17TheWord** [comment]
是否安装 `Minecraft` 适配器？
```shell
nb adapter install nonebot-adapter-minecraft
```

**Comment by Zhou-Shilin** [comment]
安装后报错：
```bash
03-10 13:46:40 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
03-10 13:46:40 [DEBUG] nonebot | Succeeded to load adapter "Discord"
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/internal/driver/abstract.py", line 79, in register_adapter
    self._adapters[name] = adapter(self, **kwargs)
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/adapters/minecraft/adapter.py", line 59, in __init__
    self.minecraft_config: Config = get_plugin_config(Config)
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/plugin/__init__.py", line 120, in get_plugin_config
    return type_validate_python(config, model_dump(get_driver().config))
  File "/opt/nonebot/HypiworldConnect/.venv/lib/python3.10/site-packages/nonebot/compat.py", line 375, in type_validate_python
    return parse_obj_as(type_, data)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[Config]
__root__ -> minecraft_server_rcon
  value is not a valid dict (type=type_error.dict)
Stopped reloader.
```

**Comment by 17TheWord** [comment]
正在对插件进行更新，可以尝试升级三个包：`nonebot-adapter-minecraft`、`mcqq-tool`、`nonebot-plugin-mcqq`

**Comment by 17TheWord** [comment]
可以尝试更新 `mcqq` 全系列程序，如无问题，将关闭该issue
